defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: circleci/node:12

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json

version: 2.1
jobs:
 
  checkout:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: cd ~/repo && yarn lint

  security-check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn audit --summary


  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build

workflows:
  node-tests:
    jobs:
      - checkout
      - security-check:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - checkout
            - lint
            - test
