version: 2.1
jobs:
 
  build-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn build

  check-audit:
    docker:
        # specify the version you desire here
        - image: circleci/node:12
    steps:
      - checkout
      - run: yarn audit --sumary

  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npx eslint .

workflows:
  node-tests:
    jobs:
      - build-test
      - check-audit
      - lint
